apiVersion: apps/v1
kind: Deployment
metadata:
  name: deptser
  labels:
    app: deptser
spec:
  replicas: 2
  template:
    metadata:
      name: deptser
      labels:
        app: deptser
    spec:
      serviceAccountName: sample-sc
      containers:
        - name: deptser
          image: dept-service:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_INCLUDE
              value: "kubernetes"
            - name: name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
#          envFrom:
#            - configMapRef:
#                name: myconfig
          ports:
            - containerPort: 8089
          readinessProbe:
            httpGet:
              port: 8089
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8089
              path: /actuator/health/liveness
      restartPolicy: Always
  selector:
    matchLabels:
      app: deptser

---
apiVersion: v1
kind: Service
metadata:
  name: dept-service
spec:
  selector:
    app: deptser
  ports:
    - port: 8080
      targetPort: 8089
      nodePort: 30089
  type: NodePort

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k-name
data:
  application.yml: |-
    bean:
      greeting: Say Hello to the World
      farewell: Say Goodbye
    ---
    spring:
      profiles: development
    bean:
      greeting: Say Hello to the Developers
      farewell: Say Goodbye to the Developers
    ---
    spring:
      profiles: production
    bean:
      greeting: Say Hello to the Ops
      farewell: Say Goodbye ops