apiVersion: apps/v1
kind: Deployment
metadata:
  name: userser
  labels:
    app: userser
spec:
  replicas: 1
  template:
    metadata:
      name: userser
      labels:
        app: userser
    spec:
      serviceAccountName: sample-sc
      containers:
        - name: userser
          image: user-service:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_INCLUDE
              value: "kubernetes"
            - name: name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
#          envFrom:
#            - configMapRef:
#                name: myconfig
          ports:
            - containerPort: 8089
          readinessProbe:
            httpGet:
              port: 8089
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8089
              path: /actuator/health/liveness
      restartPolicy: Always
  selector:
    matchLabels:
      app: userser

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: userser
  ports:
    - port: 8080
      targetPort: 8089
      nodePort: 30088
  type: NodePort

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k-name
data:
  application.yml: |-
    bean:
      greeting: Say Hello to the World
      farewell: Say Goodbye
    ---
    spring:
      profiles: development
    bean:
      greeting: Say Hello to the Developers
      farewell: Say Goodbye to the Developers
    ---
    spring:
      profiles: production
    bean:
      greeting: Say Hello to the Ops
      farewell: Say Goodbye ops
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: userser-role
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: userser-binding
subjects:
  - kind: ServiceAccount
    name: sample-sc
roleRef:
  kind: Role
  name: userser-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: sample-sc
